version: '3.8'

services:
  portfolio:
    build: .
    container_name: lalo-portfolio
    restart: unless-stopped
    ports:
      - "3010:3000" # Izquierda: Puerto en tu homelab (host) | Derecha: Puerto dentro del contenedor
    environment:
      - NODE_ENV=production
